services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PHX_SERVER=true
      - PHX_HOST=${PHX_HOST}
      - PORT=4000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_BASE_URL=${MPESA_BASE_URL}
      - MPESA_SHORTCODE=${MPESA_SHORTCODE}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
      - MPESA_CALLBACK_URL=${MPESA_CALLBACK_URL}
      - DATABASE_URL_DIRECT=ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - twenty_dollar_club_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.7-alpine3.23
    container_name: twenty_dollar_club_postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - twenty_dollar_club_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer:latest
    container_name: twenty_dollar_club_adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - twenty_dollar_club_network
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - dev

volumes:
  postgres_data:
    name: twenty_dollar_club_postgres_data
    driver: local

networks:
  twenty_dollar_club_network:
    driver: bridge
